### ISSUE TITLE
Automate branch merging 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#11368]
Our usual flow is to merge bugfix releases `release` and then back to `master`. Currently, this needs the explicit interaction by someone out of the core team, mostly @Lineflyer or @moving-bits.

However, automation is a create way to optimize our workflows and save time (for coding ;-)). 

Furthermore, it sometimes happens that important Bugfixes are only contained in `release` branch but are missing in the nightlys for some days. 

This could be improved by using Jenkins or Github Actions. Jenkins would probably need a crown job, while with Github Actions we can even set "push to `release`" as trigger directly, which is IMHO the preferred solution. 

[Github Actions](https://github.com/cgeo/cgeo/actions) is completely free for public repositories. 

If we decide to  do so, we should set up the flow with  Github Actions as follow:
- use `push to release branch` as trigger 
- apply our merge strategy "ours" 
- check if branch heads are equal, if so do nothing (maybe git is doing that automatically)  
- create a `merge branch 'release'` commit
- only use a regular push, no force  push (if there are merge conflicts a team member will still need to do the merge manually)

Please tell me if you like the idea or if there are any situations where `release` should explicitly not be merged to `master`.

**Comment by Lineflyer** [comment]
As we should and will always merge back changes from `release` to `master` there is no situation where this should explicitly not done. 

So this is a good idea in general!
I have no idea about the capability of such Github actions...feel free to explore.

You already mentioned all the important points, like:
- Apply merge strategy "ours"
- No force push

Maybe it should be done only once a day or keep several hours in between, because if some PRs are merged one after another we will otherwise have a lot of noise by "Merge branch release" commits and corresponding CI builds.

**Comment by eddiemuc** [comment]
One question: what happens if such an automatic merge attempt results in merge conflicts? Will there be some sort of warning and request for manual resolution?

**Comment by fm-sys** [comment]
> Will there be some sort of warning and request for manual resolution?

Currently nothing. But until now, everything is just a raw idea in my head. But we can think about something meaningful. ;-)

I will assign this issue to me, let's see if I can come up with something suitable...

**Comment by fm-sys** [comment]
I created a test repository:
https://github.com/fm-sys/git-actions-branch-merge-test

After some back and forth, I reached a state which IMHO is quite reasonable... 

The flow will be triggered at 0:00 or a manual activation. 

0:00 is probably in UTC. So maybe we need to adapt the time so the flow runs half an hour before the nightly is generated. 

```
name: Auto-merge branches 


on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

env:
  REPO: https://fm-sys:${{secrets.GITHUB_TOKEN}}@github.com/fm-sys/git-actions-branch-merge-test.git
  RELEASE_BRANCH: release
  MASTER_BRANCH: master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "merge-branches"
  merge-branches:
    runs-on: ubuntu-latest

    steps:
      # Runs a set of commands using the runners shell
      - name: Clone and setup the repo
        run: |
          git clone ${{env.REPO}} -b ${{env.MASTER_BRANCH}} tmp
          cd tmp
          # git config --local include.path ../.gitconfig
          git config user.name cgeo branch-merge-bot
          git config user.email 61464155+cgeo-ci-bot@users.noreply.github.com
      - name: Merge branches and push 
        run: | 
          cd tmp    # path is reseted for every step 
          git merge origin/${{env.RELEASE_BRANCH}} -m "merge branch '${{env.RELEASE_BRANCH}}'"
          git push
```

![Screenshot_20210801_192921_org mozilla firefox_copy_432x1092](https://user-images.githubusercontent.com/64581222/127780106-6a6e6c71-2662-44d4-b35c-3554d0e777c4.jpg)

When merge fails, an email is sent (to repository owner/watchers?!). Don't know what will happen exactly for organization repositories though... We just need to try it out. 

![Screenshot_20210801_190107_com google android gm_copy_432x936](https://user-images.githubusercontent.com/64581222/127780126-f7480bab-6c88-4116-b065-b9fa61aab262.jpg)
