### ISSUE TITLE
Native crash on Android 7 "in tgkill"

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6669]
I am noticing quite a bunch of crash reports on Google Play refering to "native crash in tgkill" only providing a backtrace like this:
```
backtrace:
  native: pc 000000000006ca30  /system/lib64/libc.so (tgkill+8)
  native: pc 0000000000069eb8  /system/lib64/libc.so (pthread_kill+64)
  native: pc 0000000000024198  /system/lib64/libc.so (raise+24)
  native: pc 000000000001c9b0  /system/lib64/libc.so (abort+52)
  native: pc 0000000000011500  /system/lib64/libcutils.so (__android_log_assert+252)
  native: pc 000000000010fae8  /system/lib64/libandroid_runtime.so (_ZNK7android6Bitmap11assertValidEv+40)
  native: pc 000000000010fbcc  /system/lib64/libandroid_runtime.so (_ZN7android6Bitmap11getSkBitmapEP8SkBitmap+20)
  native: pc 000000000010bc34  /system/lib64/libandroid_runtime.so
  native: pc 000000000243df00  /system/framework/arm64/boot-framework.oat (android.graphics.Canvas.nativeDrawBitmapMatrix+172)
  native: pc 0000000002442618  /system/framework/arm64/boot-framework.oat (android.graphics.Canvas.drawBitmap+148)
  native: pc 0000000000009070  /dev/ashmem/dalvik-jit-code-cache_7227_7227 (deleted)
```

Using Google for this kind of crashes shows many thready of app having similar problems and partly solve it. But I cannot judge what is written there....maybe someone else can investigate.

In fact it is happening in c:geo for
- Android 7.0 and 7.1 device
- Device list shows Samsung, Google, LG and Sony devices (maybe also others)

**Comment by SammysHP** [comment]
See https://github.com/mapsforge/mapsforge/issues/957.

**Comment by ragaisis** [comment]
@tobrun I've got probably same issue with Mapbox 5.1.3 Android SDK on various devices. For example:

Sony Xperia Z5 (E6653), 3072MB RAM, Android 7.1  Report 1 of 92

```
backtrace:
  native: pc 0000000000049e78  /system/lib/libc.so (tgkill+12)
  native: pc 00000000000475f3  /system/lib/libc.so (pthread_kill+34)
  native: pc 000000000001d809  /system/lib/libc.so (raise+10)
  native: pc 0000000000019301  /system/lib/libc.so (__libc_android_abort+34)
  native: pc 0000000000017368  /system/lib/libc.so (abort+4)
  native: pc 000000000001b803  /system/lib/libc.so (__libc_fatal+22)
  native: pc 00000000000194fb  /system/lib/libc.so (__assert2+18)
  native: pc 00000000002be59b  /data/app/com.our.app.beta-1/lib/arm/libmapbox-gl.so
  native: pc 000000000038adf7  /data/app/com.our.app.beta-1/lib/arm/libmapbox-gl.so
  native: pc 0000000000393f83  /data/app/com.our.app.beta-1/lib/arm/libmapbox-gl.so
  native: pc 0000000000227867  /data/app/com.our.app.beta-1/lib/arm/libmapbox-gl.so
  native: pc 00000000001bc789  /data/app/com.our.app.beta-1/lib/arm/libmapbox-gl.so
  native: pc 00000000001bce49  /data/app/com.our.app.beta-1/lib/arm/libmapbox-gl.so
  native: pc 00000000000b7ec3  /data/app/com.our.app.beta-1/lib/arm/libmapbox-gl.so
  native: pc 00000000000cdde7  /data/app/com.our.app.beta-1/lib/arm/libmapbox-gl.so
  native: pc 00000000000cdd7d  /data/app/com.our.app.beta-1/lib/arm/libmapbox-gl.so
  native: pc 00000000000cdd45  /data/app/com.our.app.beta-1/lib/arm/libmapbox-gl.so
  native: pc 00000000000cde71  /data/app/com.our.app.beta-1/lib/arm/libmapbox-gl.so
  native: pc 00000000000cde31  /data/app/com.our.app.beta-1/lib/arm/libmapbox-gl.so
  native: pc 00000000007bd657  /data/app/com.our.app.beta-1/oat/arm/base.odex
```

More statistics from google play crash report page:

Android version  |  Percentage
--  | --
Android 7.0 | 44%
Android 7.1 | 25%
Android 6.0 | 23%



Device  | Times crashed  
-- | --
Xperia Z5 (E6653) | 25
DROID MAXX 2 (lux) | 17
Honor 8 (HWFRD) | 15
Galaxy S7 (herolte) | 11
Others | 24




Maybe it's somehow related to this https://developer.android.com/about/versions/nougat/android-7.0-changes.html#ndk
